# Generated by Django 6.0.5 on 2026-05-31 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fachgebiet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kursbeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kurs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.kurs')),
            ],
        ),
        migrations.AddField(
            model_name='kurs',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='studenten',
            field=models.ManyToManyField(to='university.student'),
        ),
        migrations.CreateModel(
            name='Studentenausweis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausweis_nr', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
            ],
        ),
    ]
